name: CI

on:
  push:
    branches:
      - main

jobs:
  # build:
  #   name: Package Build ğŸª›
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Use Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '14.x'
      
  #     - name: Installing Packages ğŸ“
  #       run: npm install

  #     - name: Building Application ğŸ
  #       run: npm run build

  # unit_testing:
  #   needs: [build]
  #   name: Running units tests ğŸ§ª
  #   strategy:
  #     matrix:
  #       # os: [macos-latest, windows-latest, ubuntu-latest]
  #       # version: [12, 14, 16]

  #   runs-on: ${{ matrix.os }}

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Use Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: ${{ matrix.version }}

  #     - name: Running tests
  #       run: |
  #         npm install
  #         npm test

  release:
    # needs: [unit_testing]
    name: Creating a new release ğŸ€
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Reading JSON
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'package.json'
          prop_path: 'version'

      - run: echo ${{steps.version.outputs.prop}} 

      # - name: Create Release âœ’ï¸